services:
  redis-node-1:
    image: redis:latest
    container_name: redis-node-1
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6385:6379"
      - "16385:16379"

  redis-node-2:
    image: redis:latest
    container_name: redis-node-2
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6386:6379"
      - "16386:16379"

  redis-node-3:
    image: redis:latest
    container_name: redis-node-3
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6387:6379"
      - "16387:16379"

  redis-node-4:
    image: redis:latest
    container_name: redis-node-4
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6388:6379"
      - "16388:16379"

  redis-node-5:
    image: redis:latest
    container_name: redis-node-5
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6389:6379"
      - "16389:16379"

  redis-node-6:
    image: redis:latest
    container_name: redis-node-6
    command: redis-server --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6390:6379"
      - "16390:16379"

  cluster-creator:
    image: redis:latest
    container_name: redis-cluster-creator
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    command: >
      sh -c "sleep 5 &&
             echo 'yes' | redis-cli --cluster create 
             redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 
             redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 
             --cluster-replicas 1"
